### ISSUE TITLE
replace getters and setters in configurations with ruby convention such as attr_accessor

### ISSUE THREAD

**Issue by jdoconnor** [rosette-proj/rosette-core#22]
In our configuration objects, we often use get_abc and set_abc methods instead of the ruby convention of `def abc` and `def abc=(newvalue)`. Is this a Jruby thing?

**Comment by camertron** [comment]
It's not a JRuby thing, I just find it more method-like and intention revealing. Using `abc=(newvalue)` could just as easily be manipulating an `attr_writer`, and I explicitly wanted the configurators to be built via method calls.
